# Generated by Django 5.2.15 on 2026-06-15 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock Symbol (e.g., RELIANCE.NS)', max_length=20)),
                ('indicator', models.CharField(choices=[('RSI', 'Relative Strength Index'), ('SMA_50', '50-Day Simple Moving Average'), ('SMA_200', '200-Day Simple Moving Average'), ('MACD', 'MACD Line')], max_length=20)),
                ('condition', models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('==', 'Equal To')], max_length=10)),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
